/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kissan_connect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author vaibhav
 */
public class consumer_form1 extends javax.swing.JFrame {

    /**
     * Creates new form consumer_form1
     */
    public consumer_form1() {
        initComponents();
        
        setSize(900,800);
        setLocation(400,100);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfcrop = new javax.swing.JTextField();
        tfquantity = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Quantity (in kg's)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(95, 169, 252, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 100, 173, 43);

        table.setBackground(new java.awt.Color(255, 255, 102));
        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kissan_Id", "Price", "Negotiable", "Location", "Contact No", "Transportation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setSelectionBackground(new java.awt.Color(255, 102, 102));
        table.setSelectionForeground(new java.awt.Color(153, 255, 255));
        table.setShowVerticalLines(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 290, 742, 450);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Crop you need");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(95, 66, 252, 37);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 204));
        jButton2.setText("Search Market Value");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 160, 260, 44);

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(31, 20, 59, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 102, 200, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(370, 210, 200, 10);

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Mouse Right click to check details and Press \"B\" to buy");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 260, 480, 24);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaibhav\\Desktop\\Kissan_Images\\WhatsApp Image 2020-05-26 at 2.19.34 AM.jpeg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 800);

        tfcrop.setBackground(new java.awt.Color(102, 255, 255));
        tfcrop.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        tfcrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcropActionPerformed(evt);
            }
        });
        getContentPane().add(tfcrop);
        tfcrop.setBounds(369, 66, 200, 37);

        tfquantity.setBackground(new java.awt.Color(102, 255, 255));
        tfquantity.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        tfquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfquantityActionPerformed(evt);
            }
        });
        getContentPane().add(tfquantity);
        tfquantity.setBounds(369, 177, 200, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfquantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs = null;
        try{
            

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "");
            PreparedStatement pst = conn.prepareStatement("select Id,crop_name,price,negotiable,location,Phone_no,Transportation from kissan_data");
            rs=pst.executeQuery();
            

            DefaultTableModel tb = (DefaultTableModel) table.getModel();
            tb.setRowCount(0);
            String crop = tfcrop.getText();
            
            while (rs.next()){
//                System.out.println(rs.getString(1));
            if(rs.getString(2).equals(crop)){
                Object o[] = {rs.getString(1),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getInt(6),rs.getString(7)};
                tb.addRow(o);
//            
            }
//            else {
//                JOptionPane.showMessageDialog(rootPane, "no Such crop");
//            }
            
          }
            

        }

        catch(Exception ex){
            
            System.out.println("Code Not Executed");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfcropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcropActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UrlContent x = new UrlContent();
        String z = tfcrop.getText();
        x.url(z);
//        x.msg();
     ///////////////KEY Pressed///////////
        
        //////////////////////MOUSE Clicked///////////////

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new first().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        TableModel model = table.getModel();
        //        int  = Integer.parseInt(model.getValueAt(index,0).toString());
        String k_id = (String) model.getValueAt(index, 0);
        //        JOptionPane.showMessageDialog(rootPane, k_id);

        ResultSet rs = null;
        try{

            String msg = k_id;
            new buy(msg).setVisible(true);
//              public buy() {
        initComponents();
        setSize(800,800);
        setLocation(400,100);
    
            
            
            
            

        }

        catch(Exception ex){

            System.out.println("Code Not Executed");
        }
    }//GEN-LAST:event_tableKeyPressed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        // TODO add your handling code here:
        //        JOptionPane.showMessageDialog(rootPane, "Pressed mouse");
    }//GEN-LAST:event_tableMousePressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int index = table.getSelectedRow();
        TableModel model = table.getModel();
        //        int  = Integer.parseInt(model.getValueAt(index,0).toString());
        String k_id = (String) model.getValueAt(index, 0);
        //        JOptionPane.showMessageDialog(rootPane, k_id);

        ResultSet rs = null;
        try{

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "");
            PreparedStatement pst = conn.prepareStatement("select details from kissan_data where Id='"+k_id+"' ");
            rs=pst.executeQuery();

            while (rs.next()){
                String z = rs.getString(1);
                JOptionPane.showMessageDialog(rootPane, z);

            }

        }

        catch(Exception ex){

            System.out.println("Code Not Executed");
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consumer_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consumer_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consumer_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consumer_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consumer_form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfcrop;
    private javax.swing.JTextField tfquantity;
    // End of variables declaration//GEN-END:variables
}
