/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kissan_connect;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class kissan_form extends javax.swing.JFrame {

    /**
     * Creates new form kissan_form
     */
    public kissan_form() {
        initComponents();
        setSize(900,900);
        setLocation(400,100);
//        scaleImage();
    }
//    public void scaleImage(){
//    ImageIcon icon = new ImageIcon("C:\\Users\\vaibhav\\Desktop\\Kissan_Images");
//    Image img = icon.getImage();
//    Image imgscale = img.getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), Image.SCALE_SMOOTH);
//    ImageIcon scaledIcon = new ImageIcon(imgscale);
//    jLabel12.setIcon(scaledIcon);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbt1 = new javax.swing.JRadioButton();
        rbt3 = new javax.swing.JRadioButton();
        rbt2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        tflocation = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        tfdetails = new javax.swing.JTextField();
        tfquantity = new javax.swing.JTextField();
        tfprice = new javax.swing.JTextField();
        tfcrop = new javax.swing.JTextField();
        tfadhar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("CroP Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(68, 130, 210, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Quantity  in kg's");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 192, 290, 28);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Price (per Kg) ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(68, 253, 250, 30);

        rb1.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        rb1.setText("Negotiable");
        getContentPane().add(rb1);
        rb1.setBounds(540, 300, 190, 29);

        rb2.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        rb2.setText("Non - Negotiable");
        getContentPane().add(rb2);
        rb2.setBounds(540, 350, 190, 29);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 770, 200, 60);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Extra Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 680, 260, 35);

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("Your ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 80, 150, 35);

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("Location");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 390, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setText("Phone No");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 430, 150, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Transportation Expenses");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 510, 400, 31);

        rbt1.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup2.add(rbt1);
        rbt1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        rbt1.setText("Complete Expense");
        getContentPane().add(rbt1);
        rbt1.setBounds(540, 470, 200, 29);

        rbt3.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup2.add(rbt3);
        rbt3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        rbt3.setText("Zero Expense");
        getContentPane().add(rbt3);
        rbt3.setBounds(540, 550, 200, 29);

        rbt2.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup2.add(rbt2);
        rbt2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        rbt2.setText("Half Expense");
        getContentPane().add(rbt2);
        rbt2.setBounds(540, 510, 200, 29);

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 102));
        jLabel11.setText("Adhar No.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 620, 180, 35);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Home Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 10, 87, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(540, 110, 180, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(540, 160, 180, 10);

        jLabel13.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 102));
        jLabel13.setText("Negotiability");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 320, 310, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(540, 230, 180, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(540, 280, 180, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(540, 410, 180, 10);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(540, 450, 180, 10);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(540, 648, 180, 10);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(540, 750, 180, 10);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaibhav\\Desktop\\Kissan_Images\\Open Field.jpeg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 10, 816, 900);

        tfid.setBackground(new java.awt.Color(102, 255, 255));
        tfid.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid);
        tfid.setBounds(540, 89, 180, 20);

        tflocation.setBackground(new java.awt.Color(102, 255, 255));
        tflocation.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tflocation);
        tflocation.setBounds(540, 380, 180, 29);

        tfphone.setBackground(new java.awt.Color(102, 255, 255));
        tfphone.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tfphone);
        tfphone.setBounds(540, 420, 180, 29);

        tfdetails.setBackground(new java.awt.Color(102, 255, 255));
        tfdetails.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tfdetails);
        tfdetails.setBounds(540, 680, 180, 69);

        tfquantity.setBackground(new java.awt.Color(102, 255, 255));
        tfquantity.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tfquantity);
        tfquantity.setBounds(540, 200, 180, 29);

        tfprice.setBackground(new java.awt.Color(102, 255, 255));
        tfprice.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tfprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpriceActionPerformed(evt);
            }
        });
        getContentPane().add(tfprice);
        tfprice.setBounds(541, 250, 180, 29);

        tfcrop.setBackground(new java.awt.Color(102, 255, 255));
        tfcrop.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tfcrop);
        tfcrop.setBounds(540, 140, 180, 20);

        tfadhar.setBackground(new java.awt.Color(102, 255, 255));
        tfadhar.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        getContentPane().add(tfadhar);
        tfadhar.setBounds(540, 620, 180, 29);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      Connection conn=null;
      PreparedStatement pst=null;
      ResultSet rs = null;
      
      try{
           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","");
           pst =  conn.prepareStatement("select Id,adhar_no from login where Id=? and adhar_no=?");
                pst.setString(1,tfid.getText());
                pst.setString(2,tfadhar.getText());

                rs=pst.executeQuery();
                
                if(rs.next()){
//                      
                    try{
                           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","");
                           String sql = "INSERT INTO `kissan_data`(`Id`, `crop_name`, `quantity`, `price`, `negotiable`, `location`, `Phone_no`, `Transportation`, `details`) VALUES (?,?,?,?,?,?,?,?,?)";
//                           pst = conn.prepareStatement("INSERT INTO `kissan_data`(`Id`, `crop_name`, `quantity`, `price`, `negotiable`, `location`, `Phone_no`, `Transportation`, `details`) VALUES (?,?,?,?,?,?,?,?,?)");
                       pst = conn.prepareStatement(sql);
                       int qty = Integer.parseInt(tfquantity.getText());
                       int price = Integer.parseInt(tfprice.getText());
                       int phone_no = Integer.parseInt(tfphone.getText());

                       pst.setString(1, tfid.getText());
                       pst.setString(2, tfcrop.getText());
                       pst.setInt(3, qty);
                       pst.setInt(4, price);

                       if(rb1.isSelected())
                               {
                                   pst.setString(5, "Yes");
                               }
                               else{
                                   pst.setString(5, "No");
                               }
                       pst.setString(6, tflocation.getText());

                       pst.setInt(7,phone_no);


                       if(rbt1.isSelected())
                               {
                                   pst.setString(8, "Complete Expense");
                               }
                       else if (rbt2.isSelected()){
                                   pst.setString(8, "Half Expense");
                               }
                       else {
                                   pst.setString(8, "Zero Expense");
                       }
                       pst.setString(9, tfdetails.getText());


                       pst.executeUpdate();

                       JOptionPane.showMessageDialog(null, "Thank you, your data has been entered");



                           }

                           catch(Exception ex){
                               JOptionPane.showMessageDialog(null,"Thank you, your data has been sucessfully entered");
                           }
                                            
                                            
                }
                else{
                JOptionPane.showMessageDialog(null, "Enter your Registered Id and Adhar number");
                }
      
      }
      catch(Exception ex){
      JOptionPane.showMessageDialog(null, "Cannot Login");
      }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void tfpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpriceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfpriceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new first().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kissan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kissan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kissan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kissan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kissan_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rbt1;
    private javax.swing.JRadioButton rbt2;
    private javax.swing.JRadioButton rbt3;
    private javax.swing.JTextField tfadhar;
    private javax.swing.JTextField tfcrop;
    private javax.swing.JTextField tfdetails;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tflocation;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfprice;
    private javax.swing.JTextField tfquantity;
    // End of variables declaration//GEN-END:variables
}
