/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kissan_connect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setSize(900,800);
        setLocation(400,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        tfpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfadhar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tflocation = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(99, 57, 167, 26);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(480, 63, 125, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel2.setText("Email Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(99, 114, 188, 26);

        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid);
        tfid.setBounds(480, 120, 125, 20);
        getContentPane().add(tfpass);
        tfpass.setBounds(480, 246, 125, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(99, 240, 230, 26);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 590, 155, 53);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        rb1.setText("Kissan");
        getContentPane().add(rb1);
        rb1.setBounds(480, 396, 99, 35);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        rb2.setText("Consumer");
        getContentPane().add(rb2);
        rb2.setBounds(480, 470, 133, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel4.setText("You Are");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(99, 433, 109, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel5.setText("Adhar No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(99, 167, 175, 26);

        tfadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfadharActionPerformed(evt);
            }
        });
        getContentPane().add(tfadhar);
        tfadhar.setBounds(480, 173, 125, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel6.setText("Location");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(99, 312, 94, 26);
        getContentPane().add(tflocation);
        tflocation.setBounds(480, 318, 125, 20);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(630, 590, 130, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaibhav\\Desktop\\Kissan_Images\\man&buffalo.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 0, 800, 820);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Connection conn=null;
        PreparedStatement pst=null;
        
        try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","");
        pst = conn.prepareStatement("insert into login (Id,Password,adhar_no,Location) values(?,?,?,?)");
//        
    int adhar_no = Integer.parseInt(tfadhar.getText());
    
    pst.setString(1, tfid.getText());
    pst.setString(2, tfpass.getText());
    pst.setInt(3, adhar_no);
    pst.setString(4,tflocation.getText());
    pst.executeUpdate();
    
    JOptionPane.showMessageDialog(null, "GG");
            
            if(rb1.isSelected())
            {
                this.dispose();
                new kissan_login().setVisible(true);
            }
            else{
                this.dispose();
                new consumer_login().setVisible(true);

            }
            
        }
        
        catch(Exception ex){
            System.out.println("not Registered");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfadharActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new first().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tfadhar;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tflocation;
    private javax.swing.JPasswordField tfpass;
    // End of variables declaration//GEN-END:variables
}
