/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kissan_connect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhav
 */
public class status_check extends javax.swing.JFrame {

    /**
     * Creates new form status_check
     */
    public status_check() {
        initComponents();
        setSize(900,800);
        setLocation(400,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfcost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfyourid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfcrop = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 248, 225, 35);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setText("Offered Cost");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 341, 225, 35);

        tfname.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfname);
        tfname.setBounds(423, 239, 240, 35);

        tfcost.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfcost);
        tfcost.setBounds(423, 347, 240, 35);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel3.setText("Required Qty");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(63, 441, 225, 35);

        tfqty.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfqty);
        tfqty.setBounds(423, 447, 240, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel4.setText("Contact No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(63, 520, 211, 35);

        tfno.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfno);
        tfno.setBounds(423, 526, 240, 35);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Check Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(63, 653, 322, 53);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel5.setText("Your Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(63, 51, 195, 35);

        tfyourid.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfyourid);
        tfyourid.setBounds(431, 57, 230, 35);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 204));
        jButton2.setText("Accept ");
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 653, 250, 53);

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel6.setText("Crop Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(63, 140, 195, 35);

        tfcrop.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        getContentPane().add(tfcrop);
        tfcrop.setBounds(423, 146, 240, 35);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(760, 740, 73, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaibhav\\Desktop\\Kissan_Images\\man&lassun.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        
        try{
            
            String Id = tfyourid.getText();   
            String crop_name = tfcrop.getText();
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT `customer_name`, `nego_cost`, `quantity`, `phone_no` FROM `status` WHERE your_id= '"+Id+"' AND crop='"+crop_name+"' ");
            rs=pst.executeQuery();

            while (rs.next()){
                
                    String name = rs.getString(1);
                    Integer nego_cost = rs.getInt(2);
                    Integer quantity = rs.getInt(3);
                    Integer phone_no = rs.getInt(4);
                    
                    tfname.setText(name);
                    tfcost.setText(Integer.toString(nego_cost));
                    tfqty.setText(Integer.toString(quantity));
                    tfno.setText(Integer.toString(phone_no));
                    
            }

        }

        catch(Exception ex){

            System.out.println("Code Not Executed");
        }
        tfname.setEditable(false);
        tfcost.setEditable(false);
        tfqty.setEditable(false);
        tfno.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new first().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(status_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(status_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(status_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(status_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new status_check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfcost;
    private javax.swing.JTextField tfcrop;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfno;
    private javax.swing.JTextField tfqty;
    private javax.swing.JTextField tfyourid;
    // End of variables declaration//GEN-END:variables
}
